<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="3" total="7" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[ListnerSuite has Successfully Executed]]>
    </line>
    <line>
      <![CDATA[Browser opened Successfully]]>
    </line>
    <line>
      <![CDATA[Login Successfully]]>
    </line>
    <line>
      <![CDATA[demo TestScript has Successfully Started]]>
    </line>
    <line>
      <![CDATA[demo TestScript has Successfully Skipped]]>
    </line>
    <line>
      <![CDATA[Logout Successfully]]>
    </line>
    <line>
      <![CDATA[Login Successfully]]>
    </line>
    <line>
      <![CDATA[demo TestScript has Successfully Started]]>
    </line>
    <line>
      <![CDATA[demo TestScript has Successfully Skipped]]>
    </line>
    <line>
      <![CDATA[Logout Successfully]]>
    </line>
    <line>
      <![CDATA[Login Successfully]]>
    </line>
    <line>
      <![CDATA[demo TestScript has Successfully Started]]>
    </line>
    <line>
      <![CDATA[demo TestScript has Successfully Skipped]]>
    </line>
    <line>
      <![CDATA[Logout Successfully]]>
    </line>
    <line>
      <![CDATA[Login Successfully]]>
    </line>
    <line>
      <![CDATA[demo TestScript has Successfully Started]]>
    </line>
    <line>
      <![CDATA[demo has Successfully captured SS]]>
    </line>
    <line>
      <![CDATA[Logout Successfully]]>
    </line>
    <line>
      <![CDATA[Browser Closed Successfully]]>
    </line>
  </reporter-output>
  <suite started-at="2024-05-31T15:30:55 IST" name="ListnerSuite" finished-at="2024-05-31T15:31:08 IST" duration-ms="13095">
    <groups>
    </groups>
    <test started-at="2024-05-31T15:30:55 IST" name="Test" finished-at="2024-05-31T15:31:08 IST" duration-ms="13095">
      <class name="testscript.ListnerDemo">
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:testscript.ListnerDemo@183ec003]" started-at="2024-05-31T15:30:55 IST" name="openBrowser" finished-at="2024-05-31T15:31:04 IST" duration-ms="9365" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Browser opened Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method is-config="true" signature="logIn()[pri:0, instance:testscript.ListnerDemo@183ec003]" started-at="2024-05-31T15:31:04 IST" name="logIn" finished-at="2024-05-31T15:31:05 IST" duration-ms="648" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Login Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- logIn -->
        <test-method retried="true" signature="demo()[pri:0, instance:testscript.ListnerDemo@183ec003]" started-at="2024-05-31T15:31:05 IST" name="demo" finished-at="2024-05-31T15:31:05 IST" duration-ms="35" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testscript.ListnerDemo.demo(ListnerDemo.java:14)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[demo TestScript has Successfully Started]]>
            </line>
            <line>
              <![CDATA[demo TestScript has Successfully Skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- demo -->
        <test-method is-config="true" signature="logOut()[pri:0, instance:testscript.ListnerDemo@183ec003]" started-at="2024-05-31T15:31:05 IST" name="logOut" finished-at="2024-05-31T15:31:05 IST" duration-ms="1" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logout Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- logOut -->
        <test-method is-config="true" signature="logIn()[pri:0, instance:testscript.ListnerDemo@183ec003]" started-at="2024-05-31T15:31:05 IST" name="logIn" finished-at="2024-05-31T15:31:06 IST" duration-ms="657" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Login Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- logIn -->
        <test-method retried="true" signature="demo()[pri:0, instance:testscript.ListnerDemo@183ec003]" started-at="2024-05-31T15:31:06 IST" name="demo" finished-at="2024-05-31T15:31:06 IST" duration-ms="6" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testscript.ListnerDemo.demo(ListnerDemo.java:14)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[demo TestScript has Successfully Started]]>
            </line>
            <line>
              <![CDATA[demo TestScript has Successfully Skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- demo -->
        <test-method is-config="true" signature="logOut()[pri:0, instance:testscript.ListnerDemo@183ec003]" started-at="2024-05-31T15:31:06 IST" name="logOut" finished-at="2024-05-31T15:31:06 IST" duration-ms="2" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logout Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- logOut -->
        <test-method is-config="true" signature="logIn()[pri:0, instance:testscript.ListnerDemo@183ec003]" started-at="2024-05-31T15:31:06 IST" name="logIn" finished-at="2024-05-31T15:31:06 IST" duration-ms="698" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Login Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- logIn -->
        <test-method retried="true" signature="demo()[pri:0, instance:testscript.ListnerDemo@183ec003]" started-at="2024-05-31T15:31:06 IST" name="demo" finished-at="2024-05-31T15:31:06 IST" duration-ms="8" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testscript.ListnerDemo.demo(ListnerDemo.java:14)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[demo TestScript has Successfully Started]]>
            </line>
            <line>
              <![CDATA[demo TestScript has Successfully Skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- demo -->
        <test-method is-config="true" signature="logOut()[pri:0, instance:testscript.ListnerDemo@183ec003]" started-at="2024-05-31T15:31:07 IST" name="logOut" finished-at="2024-05-31T15:31:07 IST" duration-ms="1" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logout Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- logOut -->
        <test-method is-config="true" signature="logIn()[pri:0, instance:testscript.ListnerDemo@183ec003]" started-at="2024-05-31T15:31:07 IST" name="logIn" finished-at="2024-05-31T15:31:08 IST" duration-ms="1072" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Login Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- logIn -->
        <test-method signature="demo()[pri:0, instance:testscript.ListnerDemo@183ec003]" started-at="2024-05-31T15:31:08 IST" name="demo" finished-at="2024-05-31T15:31:08 IST" duration-ms="8" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testscript.ListnerDemo.demo(ListnerDemo.java:14)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[demo TestScript has Successfully Started]]>
            </line>
            <line>
              <![CDATA[demo has Successfully captured SS]]>
            </line>
          </reporter-output>
        </test-method> <!-- demo -->
        <test-method is-config="true" signature="logOut()[pri:0, instance:testscript.ListnerDemo@183ec003]" started-at="2024-05-31T15:31:08 IST" name="logOut" finished-at="2024-05-31T15:31:08 IST" duration-ms="2" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logout Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- logOut -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:testscript.ListnerDemo@183ec003]" started-at="2024-05-31T15:31:08 IST" name="closeBrowser" finished-at="2024-05-31T15:31:08 IST" duration-ms="255" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Browser Closed Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- testscript.ListnerDemo -->
    </test> <!-- Test -->
  </suite> <!-- ListnerSuite -->
</testng-results>
